#!/bin/bash
# for more information, check my github : https://github.com/brlndtech/monit-linux-project
echo -e ":¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨:"
echo -e ":                          MONIT LINUX FAILED LOGS                               :"
echo -e ":                                                                                :"
echo -e ":            A simple tool to monitor the failed logs on linux                   :"
echo -e ":               This logs report is valid for : `date +%d/%m/%y`                         :"
echo -e ":                          Coded by Brndtech - 2019                              :"
echo -e ":                         WORK ON DEBIAN / UBUNTU                                :" 
echo -e "¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨"
moisJour=`LANG=en_GB date '+%b  %-d'`
invalid="Failed password for invalid"
failure="pam_unix(sshd:auth): authentication failure"
suFailed="FAILED"
echo ""
echo -e "Authentification failed for unknow user (ssh / sftp connect)"
echo    "¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨"
cat /var/log/auth.log | grep "$invalid" | grep "$moisJour"
echo "" 
echo "" 
echo "Authentification failed for valid user of the system (ssh / sftp connect)"
echo "¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨"
echo""
cat /var/log/auth.log | grep "$failure" | grep "$moisJour"
echo ""  
echo "***SECURITY ISSUES*** su Authentification failed for valid user of the system (shh / sftp connect)"
echo "¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨" 
echo "" 
cat /var/log/auth.log | grep "$suFailed" | grep "$moisJour"
echo "" 

