#!/bin/bash
source /etc/skdu/Globalfunction.cfg
clear
echo "-----------------------------------------------------------------"
echo "//     SKDU - Brlndtech 2019-`date +%Y` © AIO management scripts     //";
echo " $(fdate)                                                            "   
echo "-----------------------------------------------------------------";
read -p "Start skdu ? (O/n) : " rep
rep=${rep:-O}
clear
while [ $rep == "O" ] || [ $rep == "o" ]
do
# Déclaration des variables globales : 
siroot=`whoami` # stock le resultat de la commande whoami dans usercheck
usercheck="root"
choix=99
# fin des var global 
if [ $siroot = $usercheck ]; then
isCommandsExistOrNot
   echo -e "*------------------------------------------------------------------------------*"
   echo -e "* 0)  !Startup                 12) Follow the system activities (user/process) *"
   echo -e "* 2)  Not available now !      14) Backup a folder fast folder/.tar.gz/.zip    *"
   echo -e "* 4)  Display the weather      16) Solve Apt / Dpkg Errors menu                *"
   echo -e "* 6)  apt update / apt upgrade 18) Encrypt / Decrypt File(s)                   *"
   echo -e "* 8)  apt autoremove / purge   20) SSH logs for today ? : `date +%d-%m-%y`             *"
   echo -e "* 10) Manage Users sub-menu    22) Info about your sys                         *"
   echo -e "*                                                                              *"
   echo -e "* 24) Change your IP & DNS     34) Cron for noobs tool                         *"
   echo -e "* 26) Change your hostname     36) Route summarization tool                    *"
   echo -e "* 28) Nmap sub-menu pentesting                                                 *"
   echo -e "* 30) Flsm tool                                                                *"
   echo -e "* 32) CIDR convertor                                                           *"
   echo -e "*                                                                              *"
   echo -e "*                                                                              *"
   echo -e "*                              100) Leave skdu                                 *"
   echo -e "*------------------------------------------------------------------------------*"
   read -p "Make your choice between 0-100 : " choix
   case $choix in
         0)
         /etc/skdu/src/skdu-verification-paquets.sh
         ;;
         2)
         /etc/skdu/src/skdu-date.sh
         ;;
         4) 
         /etc/skdu/src/skdu-meteo.sh
         ;;
         6)
         apt update && apt upgrade 
         ;;
         8)
	      /etc/skdu/src/skdu-autoremove-purge.sh
         ;;
         10) # sub menu for manager users
         /etc/skdu/src/skdu-manage-users-sub-menu.sh
         ;;
         12) 
         /etc/skdu/src/skdu-activities.sh
         ;;
         14)
         /etc/skdu/src/skdu-backup.sh
         ;;
         16)
         /etc/skdu/src/skdu-dpkg-apt-errors-sub-menu.sh
         ;;
         18)
         clear
         /etc/skdu/src/skdu-encrypted-message.sh
         ;;
	      20)
	      /etc/skdu/src/skdu-ssh-failed-logs.sh
         ;;
         22)
         /etc/skdu/src/skdu-info-sys.sh
         ;; 
         24)
      	 /etc/skdu/src/skdu-detect-os-for-network.sh
      	 ;;
         26)
         /etc/skdu/src/skdu-hostname.sh
         ;;
	      28)
         /etc/skdu/src/skdu-nmap-sub-menu.sh
	      ;;
	      30)
	      /etc/skdu/src/skdu-flsm.sh
      	;;
      	32)
      	/etc/skdu/src/skdu-cidr-convertor.sh
      	;;
	      34)
	      /etc/skdu/src/skdu-cron-for-noobs.sh
	      ;;
         36)
         /etc/skdu/src/skdu-route-summarization.sh
         ;;
         100)
	      clear
         echo -e " \e[92m  You have leaved skdu. See you soon :) \e[0m "
         exec bash 
         # reload bash of root for the alias (you can't directy do source /root/.bashrc) -> FUCK
         break;
         ;;
         99) # mode debug 
         read -p "Revive the programme ? (O/n)" rep
         rep=${rep:-O}
         ;;
         *)
         clear
         echo -e " \e[91m - 001 - Unknow operation, please enter a number between 0 and 100 \e[0m"
         ;;
      esac
      continue 
else 
   echo -e " \e[91m - ||| Unable to execute skdu in these conditions : please follow the README.md, to solve the problem ||| - \e[0m";
   exit; 
fi
done # end of the boucle
echo "by :)"
sleep 1
clear
